services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/storage:/app/storage

    # OR use environment directly:
    # environment:
    #   - DATABASE_URL=${DATABASE_URL}
    #   - API_KEY=${API_KEY}